autoload -U compinit && compinit
autoload zmv
unalias run-help &>/dev/null
autoload run-help
HELPDIR=/usr/local/share/zsh/help

# History
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
bindkey -v
bindkey "^R" history-incremental-pattern-search-backward

# Aliases
alias vim=nvim
alias vi=nvim
if [ -f ~/.zshrc.aliases ]; then
  source ~/.zshrc.aliases
fi

# Export ENV variables
export EDITOR=nvim
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export PATH="/usr/local/heroku/bin:$PATH"
export PATH=/usr/local/sbin:/usr/local/bin:$PATH
export VISUAL=nvim

# Exclude some alias tips
export ZSH_PLUGINS_ALIAS_TIPS_EXCLUDES="vi vim nvim"

# Private ENV vars
if [ -f ~/.zshrc.env ]; then
  source ~/.zshrc.env
fi

unsetopt correct_all

# Customize to your needs...
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Tmuxinator config
if [ -f ~/.tmuxinator.zsh ]; then
  source ~/.tmuxinator.zsh
fi

# Antibody
source ~/.zsh_plugins.sh
autoload -U promptinit; promptinit
setopt noprompt{bang,cr,percent,subst} "prompt${^prompt_opts[@]}"
setopt autocd

# Attach to/create tmux session
if [ -z "$TMUX" ]
then
    mux shell
fi
